const data = [
  {
    id: 'MLB1265644164',
    site_id: 'MLB',
    title: 'Fone De Ouvido Headphone Bluetooth Tedge',
    seller: {
      id: 418149407,
      permalink: 'http://perfil.mercadolivre.com.br/TEMAKLA+BRASIL',
      power_seller_status: null,
      car_dealer: false,
      real_estate_agency: false,
      tags: [],
    },
    price: 129,
    currency_id: 'BRL',
    available_quantity: 500,
    sold_quantity: 500,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2040-04-12T16:59:14.000Z',
    condition: 'new',
    permalink:
      'https://produto.mercadolivre.com.br/MLB-1265644164-fone-de-ouvido-headphone-bluetooth-tedge-_JM',
    thumbnail:
      'http://mlb-s1-p.mlstatic.com/855848-MLB32879163232_112019-I.jpg',
    accepts_mercadopago: true,
    installments: {
      quantity: 12,
      amount: 10.75,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SP',
      state_name: 'São Paulo',
      city_id: 'QlItU1BDYWphbWFy',
      city_name: 'Cajamar',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: ['fulfillment', 'fbm_in_progress', 'mandatory_free_shipping'],
      logistic_type: 'fulfillment',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SP',
        name: 'São Paulo',
      },
      city: {
        id: 'QlItU1BDYWphbWFy',
        name: 'Cajamar',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        value_struct: null,
        source: 3376461333454861,
        id: 'ALPHANUMERIC_MODEL',
        value_id: '-1',
        value_name: null,
        values: [
          {
            id: '-1',
            name: null,
            struct: null,
            source: 3376461333454861,
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        name: 'Modelo alfanumérico',
      },
      {
        name: 'Marca',
        value_id: '8039499',
        value_struct: null,
        attribute_group_id: 'OTHERS',
        id: 'BRAND',
        value_name: 'Tedge',
        values: [
          {
            name: 'Tedge',
            struct: null,
            source: 4060709329251625,
            id: '8039499',
          },
        ],
        attribute_group_name: 'Outros',
        source: 4060709329251625,
      },
      {
        name: 'Modelo detalhado',
        value_name: null,
        value_struct: null,
        attribute_group_id: 'OTHERS',
        source: 3376461333454861,
        id: 'DETAILED_MODEL',
        value_id: '-1',
        values: [
          {
            id: '-1',
            name: null,
            struct: null,
            source: 3376461333454861,
          },
        ],
        attribute_group_name: 'Outros',
      },
      {
        id: 'ITEM_CONDITION',
        value_struct: null,
        values: [
          {
            source: 1,
            id: '2230284',
            name: 'Novo',
            struct: null,
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        name: 'Condição do item',
        value_id: '2230284',
        value_name: 'Novo',
        source: 1,
      },
      {
        id: 'LINE',
        name: 'Linha',
        value_struct: null,
        values: [
          {
            id: '7446666',
            name: 'Bluetooth',
            struct: null,
            source: 3376461333454861,
          },
        ],
        attribute_group_id: 'OTHERS',
        source: 3376461333454861,
        value_id: '7446666',
        value_name: 'Bluetooth',
        attribute_group_name: 'Outros',
      },
      {
        name: 'Modelo',
        attribute_group_name: 'Outros',
        attribute_group_id: 'OTHERS',
        source: 3376461333454861,
        id: 'MODEL',
        value_id: '8582008',
        value_name: 'Auricular Bluetooth',
        value_struct: null,
        values: [
          {
            id: '8582008',
            name: 'Auricular Bluetooth',
            struct: null,
            source: 3376461333454861,
          },
        ],
      },
    ],
    differential_pricing: {
      id: 33580182,
    },
    original_price: 149,
    category_id: 'MLB196208',
    official_store_id: 2359,
    domain_id: 'MLB-HEADPHONES',
    catalog_product_id: 'MLB15743920',
    tags: [
      'good_quality_picture',
      'good_quality_thumbnail',
      'loyalty_discount_eligible',
      'brand_verified',
      'dragged_bids_and_visits',
      'immediate_payment',
      'cart_eligible',
      'shipping_guaranteed',
    ],
  },
  {
    id: 'MLB1493710528',
    site_id: 'MLB',
    title: 'Fone Bluetooth Wireless Kimaster K3 Certificado Anatel',
    seller: {
      id: 331888701,
      permalink: 'http://perfil.mercadolivre.com.br/M+CORDEIRO',
      power_seller_status: null,
      car_dealer: false,
      real_estate_agency: false,
      tags: [],
      eshop: {
        nick_name: 'M CORDEIRO',
        eshop_rubro: null,
        eshop_id: 411967,
        eshop_locations: [],
        site_id: 'MLB',
        eshop_logo_url:
          'http://resources.mlstatic.com/eshops/331888701v53165b.png',
        eshop_status_id: 1,
        seller: 331888701,
        eshop_experience: 0,
      },
    },
    price: 89.9,
    currency_id: 'BRL',
    available_quantity: 1,
    sold_quantity: 50,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_special',
    stop_time: '2040-06-02T22:57:20.000Z',
    condition: 'new',
    permalink:
      'https://produto.mercadolivre.com.br/MLB-1493710528-fone-bluetooth-wireless-kimaster-k3-certificado-anatel-_JM',
    thumbnail:
      'http://mlb-s1-p.mlstatic.com/727532-MLB41391941269_042020-I.jpg',
    accepts_mercadopago: true,
    installments: {
      quantity: 12,
      amount: 8.78,
      rate: 17.15,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SP',
      state_name: 'São Paulo',
      city_id: 'BR-SP-44',
      city_name: 'São Paulo',
    },
    shipping: {
      free_shipping: false,
      mode: 'me2',
      tags: ['fulfillment'],
      logistic_type: 'fulfillment',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SP',
        name: 'São Paulo',
      },
      city: {
        id: 'BR-SP-44',
        name: 'São Paulo',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        name: 'Marca',
        value_id: '3325434',
        value_name: 'Kimaster',
        attribute_group_name: 'Outros',
        id: 'BRAND',
        value_struct: null,
        values: [
          {
            id: '3325434',
            name: 'Kimaster',
            struct: null,
            source: 6808261514773724,
          },
        ],
        attribute_group_id: 'OTHERS',
        source: 6808261514773724,
      },
      {
        value_id: '2230284',
        attribute_group_id: 'OTHERS',
        source: 6808261514773724,
        id: 'ITEM_CONDITION',
        value_name: 'Novo',
        value_struct: null,
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 6808261514773724,
          },
        ],
        attribute_group_name: 'Outros',
        name: 'Condição do item',
      },
      {
        value_name: 'HeadPhone Sem fio',
        value_struct: null,
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        source: 6808261514773724,
        id: 'LINE',
        name: 'Linha',
        value_id: null,
        values: [
          {
            name: 'HeadPhone Sem fio',
            struct: null,
            source: 6808261514773724,
            id: null,
          },
        ],
      },
      {
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        value_id: null,
        name: 'Modelo',
        value_name: 'K3 Certificado Anatel',
        value_struct: null,
        values: [
          {
            struct: null,
            source: 6808261514773724,
            id: null,
            name: 'K3 Certificado Anatel',
          },
        ],
        source: 6808261514773724,
        id: 'MODEL',
      },
    ],
    original_price: null,
    category_id: 'MLB196208',
    official_store_id: null,
    domain_id: 'MLB-HEADPHONES',
    catalog_product_id: null,
    tags: [
      'good_quality_thumbnail',
      'loyalty_discount_eligible',
      'good_quality_picture',
      'immediate_payment',
      'cart_eligible',
      'shipping_guaranteed',
    ],
  },
];

export default data;
